# Generated by Django 3.2.4 on 2023-12-22 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(default=2, null=True),
        ),
    ]
