# Generated by Django 5.0 on 2023-12-21 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id_candidature', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('score', models.IntegerField(default=0)),
                ('reqexp', models.CharField(max_length=50)),
                ('reqfor', models.CharField(max_length=50)),
                ('reqskill', models.CharField(max_length=100)),
                ('status', models.CharField(default='Waiting', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('person_name', models.CharField(max_length=255)),
                ('pays', models.CharField(max_length=255, null=True)),
                ('person_email', models.EmailField(max_length=255)),
                ('tel', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id_job', models.AutoField(primary_key=True, serialize=False)),
                ('domain', models.CharField(max_length=55)),
                ('company', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=255)),
                ('job_description', models.TextField()),
                ('job_salaire', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('formationreq', models.CharField(max_length=100)),
                ('expreq', models.IntegerField()),
                ('skillreq', models.CharField(max_length=255)),
                ('reportnum', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
