# Generated by Django 5.0 on 2023-12-21 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('startyear', models.DateField(blank=True, null=True)),
                ('endyear', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formation', models.CharField(max_length=255)),
                ('school', models.CharField(blank=True, max_length=255, null=True)),
                ('startyear', models.DateField(blank=True, null=True)),
                ('endyear', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=250, null=True)),
                ('prenom', models.CharField(blank=True, max_length=250, null=True)),
                ('ville', models.CharField(max_length=250)),
                ('date', models.DateField()),
                ('tel', models.IntegerField(blank=True, null=True)),
                ('genre', models.CharField(blank=True, max_length=191, null=True)),
                ('_select', models.CharField(blank=True, max_length=100, null=True)),
                ('cv', models.FileField(null=True, upload_to='cv/')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('date_naissance', models.DateField()),
                ('genre', models.CharField(max_length=255)),
                ('ville', models.CharField(max_length=255)),
                ('pays', models.CharField(max_length=255, null=True)),
                ('tel', models.CharField(max_length=20)),
                ('domaine', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=255)),
            ],
        ),
    ]
